Repository AMPerez04/SP2025_Group_1, pull requests merged in 2025-04, with the labels that each got.

#52 added candlechart.tsx
  backend/.gitignore
  backend/assets/asset_cron
  backend/main.py
  docker-compose.yml
  frontend/app/dashboard/components/visualizations/candlechart.tsx
  frontend/app/dashboard/components/visualizations/timeperiodselector.tsx
  frontend/app/dashboard/page.tsx
  frontend/zustand/store.ts
Labels: BETA

#49 BETA USER TESTING: Dashboard Overview - Learn More opens in new tab
  backend/assets/asset_collection.py
  frontend/app/dashboard/components/asset-info/asset-info.tsx
Labels: user-testing, BETA

#55 BETA USER TESTING: Graphs: Fixes graph scroll view
  frontend/app/dashboard/components/visualizations/timeperiodselector.tsx
Labels: bug, user-testing, BETA

#59 Assets - Search Query Bug Fix
  frontend/zustand/store.ts
Labels: bug, FINAL

#60 Kubernetes
  backend/Dockerfile.release
  frontend/Dockerfile.release
  frontend/zustand/store.ts
  k8s/clusters.yaml
  k8s/deployment.yaml
Labels: FINAL

#73 FINAL USER TESTING - Blank Survey Sectors Fix
  backend/main.py
Labels: bug, user-testing, FINAL
