Repository AMPerez04/SP2025_Group_1, pull requests merged in 2025-03, with the labels that each got.

#39 MVP USER TESTING: Search - Gray out stocks already in watchlist
  frontend/app/dashboard/components/sidebar/searchbar.tsx
  frontend/zustand/store.ts
Labels: MVP, user-testing

#37 MVP USER TESTING: Market Open/Close Timezone Bug Fix
  frontend/app/dashboard/components/asset-header.tsx
  frontend/app/dashboard/components/sidebar/searchbar.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/zustand/store.ts
Labels: bug, MVP, user-testing

#35 MVP USER TESTING: Branding
  README.md
  frontend/app/dashboard/components/asset-header.tsx
  frontend/app/dashboard/components/sidebar/product.tsx
  frontend/app/dashboard/components/sidebar/searchbar.tsx
  frontend/app/favicon.ico
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/logo.svg
  frontend/public/assets/placeholder.png
  frontend/public/favicon.ico
  frontend/zustand/store.ts
  package-lock.json
Labels: MVP, user-testing

#23 Dashboard Area Chart
  backend/.gitignore
  backend/analytics/__init__.py
  backend/analytics/arima_model.py
  backend/analytics/data_fetcher.py
  backend/analytics/predictor.py
  backend/main.py
  backend/requirements.txt
  frontend/app/dashboard/components/asset-header.tsx
  frontend/app/dashboard/components/visualizations/areachart.tsx
  frontend/app/dashboard/components/visualizations/dashboardCards.tsx
  frontend/app/dashboard/components/visualizations/forecastchart.tsx
  frontend/app/dashboard/components/visualizations/timeperiodselector.tsx
  frontend/app/dashboard/page.tsx
  frontend/app/globals.css
  frontend/app/reset-password/page.tsx
  frontend/components/ui/progressbar.tsx
  frontend/components/ui/radiogroup.tsx
  frontend/lib/utils.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/zustand/store.ts
Labels: MVP

#42 Docker
  .dockerignore
  .github/workflows/rufflint.yaml
  .gitignore
  README.md
  backend/Dockerfile
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/zustand/store.ts
Labels: BETA
